{% set version = "3.2.1" %}

package:
    name: mlpack
    version: {{ version }}

source:
    fn: mlpack-{{ version }}.tar.gz
    url: http://www.mlpack.org/files/mlpack-{{ version }}.tar.gz
    sha256: 3fa25157a0a6e91fd5ba223ebd911e5d86c0664d969ea3f7768d823448562f36

build:
  number: 0
  skip: true  # [win or osx]
  patches:
    - cmake-patch.patch

requirements:
  build:
    - pkg-config
    - cmake
    - make
    - cotire
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.24
    - setuptools
    - boost <1.70
    - python
    - numpy
    - pandas  >=0.15.0
    - armadillo >=6.500.0
    - pytest-runner
    - openblas
    - ensmallen >=2.10.0
    - libcblas
    - libblas
  run:
    - boost <1.70
    - python
    - pandas  >=0.15.0
    - armadillo >=6.500.0
    - openblas
    - {{ pin_compatible('numpy') }}
    - ensmallen >=2.10.0
test:
  imports:
    - mlpack
    - mlpack.knn
  commands:
    - mlpack_knn --help

about:
    home: http://www.mlpack.org
    license: BSD-3.0
    license_file: LICENSE.txt
    summary: 'mlpack a fast, flexible machine learning library'
    description: |
      mlpack is an intuitive, fast, and flexible C++ machine learning library
      with bindings to other languages. It is meant to be a machine learning analog
      to LAPACK, and aims to implement a wide array of machine learning methods and
      functions as a "swiss army knife" for machine learning researchers. In addition
      to its powerful C++ interface, mlpack also provides command-line programs and
      Python bindings.
    doc_url: http://www.mlpack.org/docs.html
    dev_url: https://github.com/mlpack/mlpack

extra:
    recipe-maintainers:
      - marcelotrevisani
