{% set version = "4.3.0" %}

package:
  name: mlpack
  version: {{ version }}

source:
  url: http://www.mlpack.org/files/mlpack-{{ version }}.tar.gz
  sha256: 08cd54f711fde66fc3b6c9db89dc26776f9abf1a6256c77cfa3556e2a56f1a3d

build:
  number: 0
  script_env:
    - CXXFLAGS="-D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]

requirements:
  build:
    - pkg-config
    - cmake
    - make
    - ninja  # [win]
    - cotire
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.24
    - setuptools
    - cereal
    - python
    - numpy
    - pandas  >=0.15.0
    - armadillo >=9.800.0
    - pytest-runner
    - openblas
    - ensmallen >=2.10.0
    - libcblas
    - libblas
    - pip
  run:
    - python
    - pandas  >=0.15.0
    - armadillo >=9.800.0
    - openblas
    - {{ pin_compatible('numpy') }}
    - ensmallen >=2.10.0
test:
  imports:
    - mlpack
    - mlpack.knn
  commands:
    - mlpack_knn --help

about:
  home: http://www.mlpack.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'mlpack: a fast, header-only machine learning library'
  description: |
    mlpack is an intuitive, fast, and flexible C++ machine learning library
    with bindings to other languages. It is meant to be a machine learning analog
    to LAPACK, and aims to implement a wide array of machine learning methods and
    functions as a "swiss army knife" for machine learning researchers. In addition
    to its powerful C++ interface, mlpack also provides command-line programs and
    Python bindings.
  doc_url: http://www.mlpack.org/docs.html
  dev_url: https://github.com/mlpack/mlpack

extra:
  recipe-maintainers:
    - marcelotrevisani
    - zoq
    - rcurtin
    - coatless
