{% set version = "3.0.4" %}
{% set build_number = 1000 %}

{% set variant = "openblas" %}
{% set build_number = build_number + 200 %}


package:
    name: mlpack
    version: {{ version }}

source:
    fn: mlpack-{{ version }}.tar.gz
    url: http://www.mlpack.org/files/mlpack-{{ version }}.tar.gz
    sha256: d02a84fdc7a3b07064f2dcb925b6a1d109f5e99eed990a4552c50ab7a9fd69cc
    patches: edit_python_cmake.patch

build:
  number: {{ build_number }}
  skip: true  # [win or osx]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake >=3.3.2
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config

  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cython >=0.24
    - setuptools
    - boost
    - python
    - numpy
    - pandas  >=0.15.0
    - armadillo >=6.500.0
    - pytest-runner
    - blas 1.1 {{ variant }}
    - openblas

  run:
    - boost
    - python
    - {{ pin_compatible('numpy') }}
    - pandas  >=0.15.0
    - armadillo >=6.500.0
    - blas 1.1 {{ variant }}
    - openblas

test:
  imports:
    - mlpack
    - mlpack.knn
  commands:
    - mlpack_knn --help

about:
    home: http://www.mlpack.org
    license: BSD-3.0
    license_file: LICENSE.txt
    summary: 'mlpack a fast, flexible machine learning library'
    description: |
      mlpack is an intuitive, fast, and flexible C++ machine learning library
      with bindings to other languages. It is meant to be a machine learning analog
      to LAPACK, and aims to implement a wide array of machine learning methods and
      functions as a "swiss army knife" for machine learning researchers. In addition
      to its powerful C++ interface, mlpack also provides command-line programs and
      Python bindings.
    doc_url: http://www.mlpack.org/docs.html
    dev_url: https://github.com/mlpack/mlpack

extra:
    recipe-maintainers:
      - marcelotrevisani
