travis:
  secure:
    BINSTAR_TOKEN: SltRPfJt0V2VGfFHZaDpMqMo1/hcEQWK5REMvnI22wfUBapR68NPfcYLS7Zw6bMS+clBaoVsZgkPkoTvsHJMkqAYKJrJfLB6pec0jWVtBiaXed1HnzMP2d+MMNKYGDmN4Z4oDV0rbHSJL7DlnjtpsaT+3VYHNfWCcIQAa+EhoO8DP+bpuwMTf/HCSYdUG5EDuA/3qwSoCyxucycY7zpvkQLVLBRdgik2faDP4GrlRE6Uem+BlAa7zR8LPndUQmWy5iHxOEfC7rm6iFKEF6LocF6Dis9K2gMCSS5EmhOOURYmF1KvPwWqEy8SvKB1RZSY7yj3Q3NsL1wdOox1GcAikqu3IESX1sYh+Gu4DWwuYnQif7iWhvVgvrCxS7160dHnt3xkvwSPVFEbp8RWbVyPneeSVQv+EGTboRUzoI2XKAyygUN05uy49Eh2X7WioZ8AbTvJB+JiveL+VpyjTo+5kh2c5B7oTvnYyJpsOOydc6kkyA/HOGiFmGn8hc6AK+3sH8B+PMuw1hWB1VS+917hu72vb+2lAkt245RPcQZKmuuS1dpy/aUAB5RKpoflUo9uc8UCT3CndvnuUbBCWKiMeH1ScaVL9bxre1vFvGUOAG4h5HKveMIjDoD3B8UOp5ImERBwT/ghJ+rcZ4YZl+bjkof8kmN8v0vC9iqg/3ootZw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
