appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: kHJQ0x/cjQmKf19nAoJw7M0BwstuBYXFgRb2aiWUvwo4OUDlGo0raSluXs0LjORvM5qkwZfZobjBgNZ1la/rR90a4cBTTYDQWy+ZAg62UGnakhihXfHpCwPzyFfGewUO729XldufUWthto5EXQIfnF3cCdHXFz0S4CKwtfZjXCdVfYXvgqWRqbVvS6a/pov7DPkvsl+hyL7TWGYih8O+7yylZiX8VukfMD8/5EzCgct/mDj18U1RK4xbCDlVm9EQ5kgGW+kcTCI+tTUjFyOmn7fOTvM1G/Hu3ByrWZV0HWJ4Nh/4n2c6USSW5UaI9aAjR8NGo41i3LOlucfwZNbMrcldHTFvGjw9d7whbWCiukeHR5lOaMZZ64Qf+DA0bGAfgezoNuWACF/g00Sujk1rgv/JdmkTqJgDYOddP72WFt7AQ1CVUw6m+Y1aB4E1js7cIkrvaS/aTqjzwxNMJKAHFUrHXKOtqdqj7lv/gOBYOCLmwwGNL4xWDzDRiPvkK2MOcGFk11/nVSWM4bsVSvHrz9AuUufOuJfhUPHBW3U0SQcjjgvg6FezwdoIxmXK+qP5wSucvzQbwNs4xNm0kd/pr/tl26eUzBd1+q6Ak/x/oCyzQuTfA0vJ6Evy1f+sRY8/ZMm2XhKCg4I+7k/eBId5tdAg3OUP+gz6UIn8wC/qSds=}
provider:
  win: azure
conda_forge_output_validation: true
